### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by girafe** [logcb/artlist#1]
Widescreen Display
- [x] let THE ARTLIST be a link to the index
- [x] re-arrange order of categories in widescreen
- [x] render page titles in head
- [x] set date headings in mono type

Pocketsize Display
- [x] make it

Post Event Form
- [x] form layout

Search Form
- [x] form layout

**Comment by girafe** [comment]
Inquiries
- [x] ask for title font
- [x] inquire about french language

**Comment by girafe** [comment]
Programming
- [x] pushstate navigation...
- [x] filter by category...
- [x] post and update the list...
- [x] search...
- [x] access and accounts...
- [x] docker image of all code
- [x] host, domain name, SSL cert
